Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
  SSHLocation:
    Type: String
    Description: The IP address range that can be used to SSH to the EC2 instances
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  InstanceWaitHandle:
    Type: AWS::CloudFormation::WaitConditionHandle
  
  InstanceWaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    DependsOn: MyEC2Instance
    Properties:
      Handle: !Ref InstanceWaitHandle
      Count: 1
      Timeout: "3600"
  
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups:
      - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe

            # Update to the latest packages
            yum update -y

            # Get the latest CloudFormation helper scripts
            yum install -y aws-cfn-bootstrap

            # Make your configuration here
            date > /tmp/datefile
            cat /tmp/datefile

            sleep 10s

            # Signal the status from instance
            /opt/aws/bin/cfn-signal -e $? --data "This is from the EC2 instance" --reason "Build process complete." '${InstanceWaitHandle}'

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref SSHLocation

  MySNSTopic:
    Type: AWS::SNS::Topic
    DependsOn: InstanceWaitCondition
    Properties:
      TopicName: DemoTopic