Parameters:
  EnvironmentType:
    Description: Environment Name
    Type: String
    AllowedValues: [production, development]
    ConstraintDescription: only can be development or production

Mappings:
  RegionMap: 
    us-east-1:
      HVM64: ami-0c7478fd229861c57
      HVMG2: ami-0c4a11a8d0e503812
    us-west-1:
      HVM64: ami-0bdb828fd58c52235
      HVMG2: ami-066ee5fd4a9ef77f1
    eu-west-1:
      HVM64: ami-047bb4163c506cd98
      HVMG2: ami-0a7c483d527806435
    eu-west-2:
      HVM64: ami-06cd52961ce9f0d85
      HVMG2: ami-053cdd503598e4a9d
    eu-west-2:
      HVM64: ami-08569b978cc4dfa10
      HVMG2: ami-0be9df32ae9f92309
  InstanceTypeEnvironment:
    production:
      instanceType: t2.small
    development:
      instanceType: t2.micro

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", HVM64]
      InstanceType: !FindInMap [InstanceTypeEnvironment, !Ref 'EnvironmentType', instanceType]
